In [2]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size = 10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [3]:
[x[3],x[7],x[2]]

[71, 86, 14]

In [5]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [7]:
ind = np.array([[3, 7],
               [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [11]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 2])
X[row, col]

array([ 2,  5, 10])

In [16]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  2],
       [ 6,  5,  6],
       [10,  9, 10]])

In [22]:
X[row[:,np.newaxis], col]

array([[ 2,  1,  2],
       [ 6,  5,  6],
       [10,  9, 10]])

In [23]:
row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 2],
       [4, 2, 4]])

In [24]:
col

array([2, 1, 2])