In [1]:
import tensorflow as tf
x = tf.Variable(3, name='x')
y = tf.Variable(4, name='y')
f = x*x*y + y + 2

In [4]:
#way 1

sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)

print(result)
sess.close()

42


In [5]:
# way2
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval
print(result)

<bound method Tensor.eval of <tf.Tensor 'add_1:0' shape=() dtype=int32>>


In [9]:
#way3
init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    result = f.eval()
    print(result)

42


In [7]:
#way4
init = tf.global_variables_initializer()
sess = tf.InteractiveSession()
init.run()
result = f.eval()
print(result)
sess.close()

42


In [8]:
x1 = tf.Variable(1)
x1.graph is tf.get_default_graph()

True

In [10]:
w = tf.constant(3)
x = w + 2
y = x + 5
z = y * 3

with tf.Session() as sess:
    print(y.eval())
    print(z.eval())

10
30


In [11]:
with tf.Session() as sess:
    y_val, z_val = sess.run([y, z])
    print(y_val)
    print(z_val)

10
30


In [12]:
import numpy as np
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
m, n = housing.data.shape

In [13]:
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name='y')
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)
with tf.Session() as sess:
    theta_value = theta.eval()
print(theta_value)

[[ -3.71851807e+01]
 [  4.36337471e-01]
 [  9.39523336e-03]
 [ -1.07113101e-01]
 [  6.44792199e-01]
 [ -4.03380000e-06]
 [ -3.78137082e-03]
 [ -4.23484027e-01]
 [ -4.37219113e-01]]


In [14]:
A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict = {A: [[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict = {A: [[4, 5, 6], [7, 8, 9]]})

print(B_val_1)

[[ 6.  7.  8.]]


In [15]:
print(B_val_2)

[[  9.  10.  11.]
 [ 12.  13.  14.]]


In [ ]:
X = tf.placeholder(tf.float32, shape=(None, n+1), name="X")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")

batch_size =100
n_batches = int(np.ceil(m / batch_size))

def fetch_batch(epoch, batch_index, batch_size):
    
    return X_batch, y_batch

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        for batch_index in range(n_barches):
            X_batch, y_batch = fetch_batch(epoch, batch, batch_size)